ALTER TABLE  `hashtag` CHANGE  `id`  `id` INT( 10 ) NOT NULL AUTO_INCREMENT ;
ALTER TABLE  `image` CHANGE  `id`  `id` INT( 10 ) NOT NULL AUTO_INCREMENT ;
ALTER TABLE  `hashtag` CHANGE  `id`  `id` INT( 10 ) NOT NULL AUTO_INCREMENT ;
